version: "3.9"

services:
    workspace:
        image: ghcr.io/jacoblincool/workspace-full:latest
        runtime: sysbox-runc
        container_name: workspace
        command: sleep infinity
        volumes:
            - workspace-volume:/home
            - docker-cache:/var/lib/docker
        ports:
          - "2222:2222"
          - "50000-50030:50000-50030"
        restart: always

volumes:
    docker-cache: {}
    workspace-volume: {}
