version: "3.9"

services:
    workspace:
        image: ghcr.io/jacoblincool/workspace-full:latest
        runtime: sysbox-runc
        container_name: workspace
        command: sleep infinity
        volumes:
            - workspace-volume:/home
            - docker-cache:/var/lib/docker
        restart: always

volumes:
    docker-cache: {}
    workspace-volume: {}
