version: "3.9"

services:
    workspace-lite:
        build:
            context: .
            target: workspace-lite
            args:
                - USERNAME=jacob
        image: ghcr.io/jacoblincool/workspace-lite:latest
    workspace:
        build:
            context: .
            target: workspace
            args:
                - USERNAME=jacob
        image: ghcr.io/jacoblincool/workspace:latest
    workspace-full:
        build:
            context: .
            target: workspace-full
            args:
                - USERNAME=jacob
                - SSH_PORT=2222
        image: ghcr.io/jacoblincool/workspace-full:latest
