version: "3.9"

services:
    workspace:
        build:
            context: .
            target: workspace
        image: ghcr.io/jacoblincool/workspace:latest
    workspace-ssh:
        build:
            context: .
            target: workspace-ssh
        image: ghcr.io/jacoblincool/workspace-ssh:latest
