version: "3.9"

services:
    workspace-pure:
        build:
            context: .
            target: workspace-pure
        image: ghcr.io/jacoblincool/workspace-pure:latest
    workspace-lite:
        build:
            context: .
            target: workspace-lite
            args:
                - USERNAME=jacob
        image: ghcr.io/jacoblincool/workspace-lite:latest
    workspace:
        build:
            context: .
            target: workspace
            args:
                - USERNAME=jacob
        image: ghcr.io/jacoblincool/workspace:latest
    workspace-full:
        build:
            context: .
            target: workspace-full
            args:
                - USERNAME=jacob
                - SSH_PORT=2222
        ports:
          - "2222:2222"
          - "50000-50030:50000-50030"
        image: ghcr.io/jacoblincool/workspace-full:latest
